spring:
  application:
    name: platform

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      connection-test-query: SELECT 1

  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    context-path: /

coolsms:
   api-key: ${COOLSMS_API_KEY}
   api-secret: ${COOLSMS_API_SECRET}
   api-sendernumber: ${COOLSMS_API_SENDER_NUMBER}

kakao:
  rest-key: ${KAKAO_REST_KEY}
  map-key: ${KAKAO_MAP_KEY}
